-- Bulk import of 23 real Goa attractions (from Attaractions List - Sheet1.csv)
-- Run this in the Supabase SQL Editor.

-- Schema migration: the attractions table needs an image array for the
-- slider instead of the single placeholder image_url column.
alter table public.attractions drop column if exists image_url;
alter table public.attractions add column if not exists image_urls text[] not null default '{}';

delete from public.attractions where slug = 'aguada-fort'; -- superseded placeholder test row

insert into public.attractions (name, slug, description, latitude, longitude, image_urls, is_active)
values
  ('Fort Aguada', 'fort-aguada', 'Overlooking the Arabian Sea, this well-preserved 1612 Portuguese fort is famous for its iconic lighthouse and sweeping ocean views.', 15.4922519, 73.7737462, array['/attractions/fort-aguada/1.webp', '/attractions/fort-aguada/2.webp', '/attractions/fort-aguada/3.webp', '/attractions/fort-aguada/4.webp', '/attractions/fort-aguada/5.webp'], true),
  ('Reis Magos Fort', 'reis-magos-fort', 'A beautifully restored 16th-century fortress on the Mandovi River, offering rich history and stunning views of Panjim.', 15.4964068, 73.8091389, array['/attractions/reis-magos-fort/1.webp', '/attractions/reis-magos-fort/2.webp', '/attractions/reis-magos-fort/3.webp', '/attractions/reis-magos-fort/4.webp', '/attractions/reis-magos-fort/5.webp'], true),
  ('Chapora Fort', 'chapora-fort', 'An iconic North Goa landmark, known for its dramatic coastal ruins and sweeping, uninterrupted ocean sunsets.', 15.6046375, 73.7369631, array['/attractions/chapora-fort/1.webp', '/attractions/chapora-fort/2.webp', '/attractions/chapora-fort/3.webp', '/attractions/chapora-fort/4.webp', '/attractions/chapora-fort/5.webp'], true),
  ('Old Goa Church & Museum', 'old-goa-church-museum', 'Explore centuries of Goan history through awe-inspiring Portuguese churches and a museum filled with rare colonial artifacts.', 15.5008238, 73.9114061, array['/attractions/old-goa-church-museum/1.webp', '/attractions/old-goa-church-museum/2.webp', '/attractions/old-goa-church-museum/3.webp', '/attractions/old-goa-church-museum/4.webp', '/attractions/old-goa-church-museum/5.webp'], true),
  ('Panjim Church Square', 'panjim-church-square', 'A picturesque city square dominated by the striking, brilliant-white Our Lady of the Immaculate Conception Church.', 15.4986101, 73.8284895, array['/attractions/panjim-church-square/1.webp', '/attractions/panjim-church-square/2.webp', '/attractions/panjim-church-square/3.webp', '/attractions/panjim-church-square/4.webp', '/attractions/panjim-church-square/5.webp'], true),
  ('Fountainhas', 'fountainhas', 'A picturesque heritage precinct offering a slice of colonial Goa with colorful villas, quaint cafes, and winding alleys.', 15.4941033, 73.8300775, array['/attractions/fountainhas/1.webp', '/attractions/fountainhas/2.webp', '/attractions/fountainhas/3.webp', '/attractions/fountainhas/4.webp', '/attractions/fountainhas/5.webp'], true),
  ('Donapaula Jetty', 'donapaula-jetty', 'Enjoy panoramic ocean views at this iconic Goan jetty, famous for its romantic folklore and bustling promenade.', 15.4506125, 73.8029961, array['/attractions/donapaula-jetty/1.webp', '/attractions/donapaula-jetty/2.webp', '/attractions/donapaula-jetty/3.webp', '/attractions/donapaula-jetty/4.webp', '/attractions/donapaula-jetty/5.webp'], true),
  ('Bhodgeshwar Temple', 'bhodgeshwar-temple', 'A serene spiritual site in Mapusa dedicated to Lord Bodgeshwar, who is locally believed to wander the nearby fields at night to protect the town.', 15.5846637, 73.805974, array['/attractions/bhodgeshwar-temple/1.webp', '/attractions/bhodgeshwar-temple/2.webp', '/attractions/bhodgeshwar-temple/3.webp', '/attractions/bhodgeshwar-temple/4.webp', '/attractions/bhodgeshwar-temple/5.webp'], true),
  ('Arambol Sweet Lake', 'arambol-sweet-lake', 'Separated from the ocean by a strip of sand, this tranquil freshwater lagoon offers a peaceful nature retreat.', 15.697879, 73.698042, array['/attractions/arambol-sweet-lake/1.webp', '/attractions/arambol-sweet-lake/2.webp', '/attractions/arambol-sweet-lake/3.webp', '/attractions/arambol-sweet-lake/4.webp', '/attractions/arambol-sweet-lake/5.webp'], true),
  ('Divar Island', 'divar-island', 'Accessible only by ferry, this tranquil island offers a peaceful escape with winding roads, lush greenery, and old-world Goan charm.', 15.500392, 73.8774033, array['/attractions/divar-island/1.webp', '/attractions/divar-island/2.webp', '/attractions/divar-island/3.webp', '/attractions/divar-island/4.webp', '/attractions/divar-island/5.webp'], true),
  ('Shiv Temple', 'shiv-temple', 'Hidden away near Chapora Jetty, this peaceful little Shiva temple offers a tranquil escape with waves crashing against the nearby rocks.', 15.6082985, 73.7351713, array['/attractions/shiv-temple/1.webp', '/attractions/shiv-temple/2.webp', '/attractions/shiv-temple/3.webp', '/attractions/shiv-temple/4.webp', '/attractions/shiv-temple/5.webp'], true),
  ('Dear Zindagi Road', 'dear-zindagi-road', 'Made famous by the Bollywood movie Dear Zindagi, this iconic, straight road is beautifully framed by towering palm trees.', 15.5775031, 73.7841906, array['/attractions/dear-zindagi-road/1.webp', '/attractions/dear-zindagi-road/2.webp', '/attractions/dear-zindagi-road/3.webp', '/attractions/dear-zindagi-road/4.webp', '/attractions/dear-zindagi-road/5.webp'], true),
  ('Betul Fort', 'betul-fort', 'A historic 17th-century coastal fort built by Shivaji Maharaj, offering stunning views where the Sal River meets the Arabian Sea.', 15.1409989, 73.9506808, array['/attractions/betul-fort/1.webp', '/attractions/betul-fort/2.webp', '/attractions/betul-fort/3.webp', '/attractions/betul-fort/4.webp', '/attractions/betul-fort/5.webp'], true),
  ('Mormugao Fort', 'mormugao-fort', 'One of India''s oldest and most prominent natural harbors, offering a fascinating glimpse into Goa''s bustling maritime trade and coastal industry.', 15.3999401, 73.791316, array['/attractions/mormugao-fort/1.webp', '/attractions/mormugao-fort/2.webp', '/attractions/mormugao-fort/3.webp', '/attractions/mormugao-fort/4.webp', '/attractions/mormugao-fort/5.webp'], true),
  ('Cabo De Rama', 'cabo-de-rama', 'Perched high on a scenic coastal cliff, this ancient South Goa fort offers dramatic views of the turquoise Arabian Sea.', 15.1031826, 73.9255111, array['/attractions/cabo-de-rama/1.webp', '/attractions/cabo-de-rama/2.webp', '/attractions/cabo-de-rama/3.webp', '/attractions/cabo-de-rama/4.webp', '/attractions/cabo-de-rama/5.webp'], true),
  ('Calangute Beach', 'calangute-beach', 'Known as the "Queen of Beaches," this bustling stretch of golden sand is famous for its lively shacks, water sports, and vibrant nightlife.', 15.549441, 73.7534857, array['/attractions/calangute-beach/1.webp', '/attractions/calangute-beach/2.webp', '/attractions/calangute-beach/3.webp', '/attractions/calangute-beach/4.webp', '/attractions/calangute-beach/5.webp'], true),
  ('Vagator Beach', 'vagator-beach', 'Famous for its dramatic red cliffs and rocky shoreline, this laid-back North Goa beach offers spectacular sunsets and vibrant nightlife.', 15.6029835, 73.733627, array['/attractions/vagator-beach/1.webp', '/attractions/vagator-beach/2.webp', '/attractions/vagator-beach/3.webp', '/attractions/vagator-beach/4.webp', '/attractions/vagator-beach/5.webp'], true),
  ('Baga Beach', 'baga-beach', 'Famous for its electrifying nightlife along Tito''s Lane, this energetic beach is a hub of water sports, lively shacks, and non-stop entertainment.', 15.5552787, 73.7517307, array['/attractions/baga-beach/1.webp', '/attractions/baga-beach/2.webp', '/attractions/baga-beach/3.webp', '/attractions/baga-beach/4.webp', '/attractions/baga-beach/5.webp'], true),
  ('Arambol Beach', 'arambol-beach', 'A relaxed, alternative coastal paradise in North Goa, celebrated for its lively sunset gatherings, paragliding, and vibrant hippie culture.', 15.6846886, 73.7032836, array['/attractions/arambol-beach/1.webp', '/attractions/arambol-beach/2.webp', '/attractions/arambol-beach/3.webp', '/attractions/arambol-beach/4.webp', '/attractions/arambol-beach/5.webp'], true),
  ('Butterfly Beach', 'butterfly-beach', 'A hidden, crescent-shaped cove in South Goa, accessible primarily by boat and famous for its pristine sands and frequent dolphin sightings.', 15.0196019, 74.001647, array['/attractions/butterfly-beach/1.webp', '/attractions/butterfly-beach/2.webp', '/attractions/butterfly-beach/3.webp', '/attractions/butterfly-beach/4.webp', '/attractions/butterfly-beach/5.webp'], true),
  ('Palolem Beach', 'palolem-beach', 'Widely considered one of Goa''s most beautiful coastal escapes, offering a scenic bay completely surrounded by lush hills and vibrant beachfront shacks.', 15.0099648, 74.0232186, array['/attractions/palolem-beach/1.webp', '/attractions/palolem-beach/2.webp', '/attractions/palolem-beach/3.webp', '/attractions/palolem-beach/4.webp', '/attractions/palolem-beach/5.webp'], true),
  ('Miramar Beach', 'miramar-beach', 'A popular, family-friendly city beach in Panjim offering golden sands, scenic sunset views, and a calm, relaxed atmosphere.', 15.4826531, 73.8073516, array['/attractions/miramar-beach/1.webp', '/attractions/miramar-beach/2.webp', '/attractions/miramar-beach/3.webp', '/attractions/miramar-beach/4.webp', '/attractions/miramar-beach/5.webp'], true),
  ('Anjuna Beach', 'anjuna-beach', 'Famous for its iconic Wednesday Flea Market, this legendary rocky beach is a vibrant hub for bohemian culture and sunset views.', 15.5733497, 73.7409781, array['/attractions/anjuna-beach/1.webp', '/attractions/anjuna-beach/2.webp', '/attractions/anjuna-beach/3.webp', '/attractions/anjuna-beach/4.webp', '/attractions/anjuna-beach/5.webp'], true);

